### ISSUE TITLE
Incompatible dependeces

### ISSUE THREAD

**Issue by soundwave12345** [R3gm/ConversaDocs#2]
Hello, I've tried to build this notebook on colab, but it seems that there are incompatible dependeces with numpy and typing-extensions.
Here the error:

```
Successfully built llama-cpp-python
Installing collected packages: typing-extensions, numpy, diskcache, llama-cpp-python
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.5.0
    Uninstalling typing_extensions-4.5.0:
      Removing file or directory /usr/local/lib/python3.10/dist-packages/__pycache__/typing_extensions.cpython-310.pyc
      Removing file or directory /usr/local/lib/python3.10/dist-packages/typing_extensions-4.5.0.dist-info/
      Removing file or directory /usr/local/lib/python3.10/dist-packages/typing_extensions.py
      Successfully uninstalled typing_extensions-4.5.0
  Attempting uninstall: numpy
    Found existing installation: numpy 1.23.5
    Uninstalling numpy-1.23.5:
      Removing file or directory /usr/local/bin/f2py
      Removing file or directory /usr/local/bin/f2py3
      Removing file or directory /usr/local/bin/f2py3.10
      Removing file or directory /usr/local/lib/python3.10/dist-packages/numpy-1.23.5.dist-info/
      Removing file or directory /usr/local/lib/python3.10/dist-packages/numpy.libs/
      Removing file or directory /usr/local/lib/python3.10/dist-packages/numpy/
      Successfully uninstalled numpy-1.23.5
  changing mode of /usr/local/bin/f2py to 755
  changing mode of /usr/local/bin/f2py3 to 755
  changing mode of /usr/local/bin/f2py3.10 to 755
**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.56.4 requires numpy<1.24,>=1.18, but you have numpy 1.25.2 which is incompatible.
tensorflow 2.13.0 requires numpy<=1.24.3,>=1.22, but you have numpy 1.25.2 which is incompatible.
tensorflow 2.13.0 requires typing-extensions<4.6.0,>=3.6.6, but you have typing-extensions 4.7.1 which is incompatible.**
Successfully installed diskcache-5.6.3 llama-cpp-python-0.1.84 numpy-1.25.2 typing-extensions-4.7.1
Traceback (most recent call last):
  File "/content/ConversaDocs/app.py", line 39, in <module>
    dc = DocChat()
  File "/content/ConversaDocs/conversadocs/bones.py", line 102, in __init__
    self.db = load_db(self.loaded_file)
  File "/content/ConversaDocs/conversadocs/bones.py", line 71, in load_db
    embeddings = HuggingFaceEmbeddings(model_name='all-MiniLM-L6-v2') # all-mpnet-base-v2 #embeddings = OpenAIEmbeddings()
  File "/usr/local/lib/python3.10/dist-packages/langchain/embeddings/huggingface.py", line 50, in __init__
    import sentence_transformers
  File "/usr/local/lib/python3.10/dist-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/usr/local/lib/python3.10/dist-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/usr/local/lib/python3.10/dist-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 5, in <module>
    import nltk
  File "/usr/local/lib/python3.10/dist-packages/nltk/__init__.py", line 133, in <module>
    from nltk.collocations import *
  File "/usr/local/lib/python3.10/dist-packages/nltk/collocations.py", line 36, in <module>
    from nltk.metrics import (
  File "/usr/local/lib/python3.10/dist-packages/nltk/metrics/__init__.py", line 18, in <module>
    from nltk.metrics.association import (
  File "/usr/local/lib/python3.10/dist-packages/nltk/metrics/association.py", line 26, in <module>
    from scipy.stats import fisher_exact
  File "/usr/local/lib/python3.10/dist-packages/scipy/stats/__init__.py", line 608, in <module>
    from ._stats_py import *
  File "/usr/local/lib/python3.10/dist-packages/scipy/stats/_stats_py.py", line 37, in <module>
    from numpy.testing import suppress_warnings
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/__init__.py", line 11, in <module>
    from ._private.utils import *
  File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 413, in <module>
    @np._no_nep50_warning()
  File "/usr/local/lib/python3.10/dist-packages/numpy/__init__.py", line 311, in __getattr__
    if attr in __future_scalars__:
AttributeError: module 'numpy' has no attribute '_no_nep50_warning
```

**Comment by R3gm** [comment]
Hello @soundwave12345, I attempted to replicate the error in Colab, but it didn't appear for me.

https://colab.research.google.com/drive/1bHRGS2RI6rDGGFrQt_P1W_3Dy_249SJj

Could you please provide me with more information about the error or the steps you followed? This will help me in finding a solution.

**Comment by soundwave12345** [comment]
Hello @R3gm ,
I've tried again, and now it works flawlessly. Don't know what happened. Thanks for taking care of this issue.
BTW Your jupyter notebooks are wonderful.
